name: Cache Dependencies Workflow

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies  # Example path to cache, adjust to your dependencies
          key: cache-d79614a

      - name: prime-cache-d79614a
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
